### ISSUE TITLE
determine graph type for data stracture

### ISSUE THREAD

**Issue by yaslena** [DHARPA-Project/kiara_plugin.network_analysis#6]
**Module description**
Runs some checks on the data looking for self-loops, parallel edges, etc. that can help to decide which graph type suits the data structure best.

**Inputs**
- edge list
- source column name
- target column name

**Graph types**
- (the whole point of the module is to find out which graph type to use)

**Outupts**
- data contains self loops: yes or no (boolean)
- data contains paralell edges: yes or no (boolean)

**Example code**
print(nx.number_of_selfloops(G)) #returns integer
G.number_of_edges() #returns integer
duplicateRowsDF = edges[edges.duplicated(['Source', 'Target'])]
print(len(duplicateRowsDF)) #if > 0, then there are parallel edges in the dataset
...

**Comment by makkus** [comment]
Information about self loops and parallel edges is not part of the network_data properites.

Closing, feel free to reopen if I missed something.
