### ISSUE TITLE
network_graph.properties module not graph-type agnostic

### ISSUE THREAD

**Issue by yaslena** [DHARPA-Project/kiara_plugin.network_analysis#8]
**Describe the bug**
The **degree section** and the **shortest path** section are not properly set up to give complete and accurate results for directed and undirected graphs. As it is currently configured, the average shortest path can only be calculated for directed graphs. The average (cumulative) degree is only calculated if the graph is undirected, but is not shown when the graph is directed. Every graph has a cumulative degree property (directed, undirected, multi_directed ...), so there is no reason not to display that information. In the following, I will focus on the shortest path problem. In a previous version it was not possible to generate undirected graphs with kiara, so the problem did not occur.

**To Reproduce**
1. Onboard the file "JournalEdges1902.csv" and convert to table:

`kiara run --save value_item=my_edges_file file.import_from.local.file_path source=examples/data/journals/JournalEdges1902.csv`

`kiara run file.convert_to.table value_item=value:my_edges_file`

2. Create an undirected graph from the table using the **graph_type=undirected** field:

`kiara run --save graph=my_undirected_graph playground.lena.graphs.improved_from_edges_table edges_table=value:my_edges_table graph_type=undirected`

3. Use the properties module

`kiara run network_graph.properties graph=value:my_undirected_graph`

Output data
                                                                                              
  ╭─ Value: number_of_nodes ───────────────────────────────────────────────────────────────╮  
  │ 197                                                                                    │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: number_of_edges ───────────────────────────────────────────────────────────────╮  
  │ 354                                                                                    │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: density ───────────────────────────────────────────────────────────────────────╮  
  │ 0.018336268517559307                                                                   │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: average_degree ────────────────────────────────────────────────────────────────╮  
  │ 3.5939086294416245                                                                     │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: average_in_degree ─────────────────────────────────────────────────────────────╮  
  │ -- not set --                                                                          │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: average_out_degree ────────────────────────────────────────────────────────────╮  
  │ -- not set --                                                                          │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  
  ╭─ Value: average_shortest_path_length ──────────────────────────────────────────────────╮  
  │ -- not set --                                                                          │  
  ╰────────────────────────────────────────────────────────────────────────────────────────╯  

**Expected behavior**
If the graph is connected (no isolated nodes, not more than 1 component) as is the case with the sample graph in the example above, kiara should be able to calculate the average shortest path for this undirected graph. The value for this graph should be: 2.5784605834885164 

The code cannot work, because of the condition in the "def process" section for shortest path:
`if nx.is_weakly_connected(graph):` This condition only applies to directed graphs, it tests whether a directed graph is connected. To test connectivity for undirected graphs you have to use: `nx.is_connected(graph)`.
There need to be two separate conditions, one for the directed and one for the undirected case.

It would be desirable to get a hint in the output section if the graph is not connected. Then the user would know to run another module that can calculate components and isolate the largest one on which the average shortest path could be then performed in a next step.

**Comment by makkus** [comment]
Closing this as we got rid of that module. Some of the properties are now part of the network_data value itself, for others we might have to create a new module.
